# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_signin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='email',
            new_name='username',
        ),
    ]
